import type { RequestEvent } from '@sveltejs/kit';
import { sha256 } from '@oslojs/crypto/sha2';
import { encodeBase32LowerCase, encodeBase64url, encodeHexLowerCase } from '@oslojs/encoding';
import * as luxon from 'luxon'
import { createPasswordResetToken, deleteAllEmailVerificationTokens, getEmailValidationToken, getSessionByID, invalidateSession, saveEmailVerificationToken, saveSession, updateSession } from '$lib/orm/auth';

/*
This code was generated by Vite, however it was generated with Drizzle ORM
So it was adjusted to be implemented with Prisma - which has 
been refactored into the orm folder to decouple 
database calls from the server logic
*/

export const DAY_IN_MS = 1000 * 60 * 60 * 24;

export const sessionCookieName = 'auth-session';

/**
 * Function that generates a random string to be used as a token
 * @returns string
 */
export function generateToken() {
	const bytes = crypto.getRandomValues(new Uint8Array(18));
	const token = encodeBase64url(bytes);

	return token;
}

/**
 * Function that creates a record of a session in the database and saves it as lowercase hexidecimal translation
 * @param token a string token representing the session
 * @param userID the ID of the user who the session is being linked to 
 * @returns Promise<Session>
 */
export async function createSession(token: string, userID: string) {
	const sessionID = encodeHexLowerCase(sha256(new TextEncoder().encode(token)));
    const expiresAt = new Date(Date.now() + DAY_IN_MS * 30)

    const session = await saveSession(sessionID, userID, expiresAt)
	return session;
}

/**
 * Function that checks if a session token is valid, if it falls in the renewal date, the
 * session expiry date gets extended
 * @param token the string token to be validated
 * @returns Promise<{session: Session, user: User}>
 */
export async function validateSessionToken(token: string) {
	const sessionID = encodeHexLowerCase(sha256(new TextEncoder().encode(token)));

    const session = await getSessionByID(sessionID)

	if (!session) {
		return { session: null, user: null };
	}
	const sessionExpired = Date.now() >= session.expiresAt.getTime();

	if (sessionExpired) {
        await invalidateSession(session.token)
	}

	const renewSession = Date.now() >= session.expiresAt.getTime() - DAY_IN_MS * 15;

	if (renewSession) {
		const newExpiration = new Date(Date.now() + DAY_IN_MS * 30);
        await updateSession(session.token, newExpiration);
		
	}

	return { session, user: session.user };
}

export type SessionValidationResult = Awaited<ReturnType<typeof validateSessionToken>>;

/**
 * Function that sets the session cookie
 * @param event the request event
 * @param token the string token to set as the cookie value
 * @param expiresAt the exiration date of the cookie
 */
export function setSessionTokenCookie(event: RequestEvent, token: string, expiresAt: Date) {
	event.cookies.set(sessionCookieName, token, { expires: expiresAt, path: '/' });
}

/**
 * Function that deletes the session cookie
 * @param event the request event
 */
export function deleteSessionTokenCookie(event: RequestEvent) {
	event.cookies.delete(sessionCookieName, { path: '/' });
}

/**
 * Function that generates a random string to be used for the userID
 * @returns string
 */
export function generateUserId() {
	const bytes = crypto.getRandomValues(new Uint8Array(15));
	const id = encodeBase32LowerCase(bytes);
	return id;
}


/**
 * Function that deletes all previous email verification tokens
 * and creates a new token
 * @param userID The ID of the user who the email verification token is being created for
 * @returns Promise<string>
 */
export async function createEmailVerificationToken(userID: string): Promise<string> {
	// invalidate all existing tokens
    await deleteAllEmailVerificationTokens(userID);
	const token = generateToken();
    // set the token to expire in 2 hours in miiliseconds
    const expires = luxon.DateTime.now().plus({hours: 2}).toMillis()

    await saveEmailVerificationToken(token, userID, expires);
	return token;
}

/**
 * Function that checks if the email verification token exists and it has not expired
 * @param token the token value of the email verification object
 * @returns Promise<string>
 */
export const validateEmailVerificationToken = async (token: string) => {
    // retrieving the token is performed insde a transaction, to keep it atomic
	const storedToken = await getEmailValidationToken(token);

	const tokenExpires = Number(storedToken.expires);
    // verify the token is not expired
	if (tokenExpires <= luxon.DateTime.now().toMillis()) {
		throw new Error('Expired token');
	}

	return storedToken.userID;
};

/**
 * Function that creates a password reset token 
 * @param userID The ID of the user that the token is linked to
 * @returns Promise<string>
 */
export async function generatePasswordResetToken(userID: string) {
    // TODO clean up old tokens
    const token = generateToken();
        // set the token to expire in 30 minutes in miiliseconds
    const expires = luxon.DateTime.now().plus({minutes: 30}).toJSDate()
    await createPasswordResetToken(userID, token, expires);

    return token
}
