import type { RequestEvent } from '@sveltejs/kit';
import { sha256 } from '@oslojs/crypto/sha2';
import { encodeBase32LowerCase, encodeBase64url, encodeHexLowerCase } from '@oslojs/encoding';
import * as luxon from 'luxon'
import { createPasswordResetToken, deleteAllEmailVerificationTokens, getEmailValidationToken, getSessionByID, invalidateSession, saveEmailVerificationToken, saveSession, updateSession } from '$lib/orm/auth';

/*
This code was generated by Vite, however it was generated with Drizzle ORM
So it was adjusted to be implemented with Prisma - which has 
been refactored into the orm folder to decouple 
database calls from the server logic
*/

const DAY_IN_MS = 1000 * 60 * 60 * 24;

export const sessionCookieName = 'auth-session';

export function generateToken() {
	const bytes = crypto.getRandomValues(new Uint8Array(18));
	const token = encodeBase64url(bytes);

	return token;
}

export async function createSession(token: string, userID: string) {
	const sessionID = encodeHexLowerCase(sha256(new TextEncoder().encode(token)));
    const expiresAt = new Date(Date.now() + DAY_IN_MS * 30)

    const session = await saveSession(sessionID, userID, expiresAt)
	return session;
}

export async function validateSessionToken(token: string) {
	const sessionID = encodeHexLowerCase(sha256(new TextEncoder().encode(token)));

    const session = await getSessionByID(sessionID)

	if (!session) {
		return { session: null, user: null };
	}
	const sessionExpired = Date.now() >= session.expiresAt.getTime();

	if (sessionExpired) {
        await invalidateSession(session.token)
	}

	const renewSession = Date.now() >= session.expiresAt.getTime() - DAY_IN_MS * 15;

	if (renewSession) {
		const newExpiration = new Date(Date.now() + DAY_IN_MS * 30);
        await updateSession(session.token, newExpiration);
		
	}

	return { session, user: session.user };
}

export type SessionValidationResult = Awaited<ReturnType<typeof validateSessionToken>>;

export function setSessionTokenCookie(event: RequestEvent, token: string, expiresAt: Date) {
	event.cookies.set(sessionCookieName, token, { expires: expiresAt, path: '/' });
}

export function deleteSessionTokenCookie(event: RequestEvent) {
	event.cookies.delete(sessionCookieName, { path: '/' });
}

export function generateUserId() {
	const bytes = crypto.getRandomValues(new Uint8Array(15));
	const id = encodeBase32LowerCase(bytes);
	return id;
}

export async function createEmailVerificationToken(userID: string): Promise<string> {
	// invalidate all existing tokens
    await deleteAllEmailVerificationTokens(userID);
	const token = generateToken();
    // set the token to expire in 2 hours in miiliseconds
    const expires = luxon.DateTime.now().plus({hours: 2}).toMillis()

    await saveEmailVerificationToken(token, userID, expires);
	return token;
}

export const validateEmailVerificationToken = async (token: string) => {
    // retrieving the token is performed insde a transaction, to keep it atomic
	const storedToken = await getEmailValidationToken(token);

	const tokenExpires = Number(storedToken.expires);
    // verify the token is not expired
	if (tokenExpires <= luxon.DateTime.now().toMillis()) {
		throw new Error('Expired token');
	}

	return storedToken.userID;
};

export async function generatePasswordResetToken(userID: string) {
    // TODO clean up old tokens
    const token = generateToken();
        // set the token to expire in 30 minutes in miiliseconds
    const expires = luxon.DateTime.now().plus({minutes: 30}).toJSDate()
    await createPasswordResetToken(userID, token, expires);

    return token
}
